# kitty.conf - Matugen base16

foreground              #656456
background              #070605
cursor                  #656456
cursor_text_color        #070605

selection_foreground     #656456
selection_background     #2c2b25

url_color                #393125

# black
color0                  #070605
color8                  #3f3e35

# red
color1                  #705b45
color9                  #705b45

# green
color2                  #6c6553
color10                 #6c6553

# yellow
color3                  #7e6c5a
color11                 #7e6c5a

# blue
color4                  #393125
color12                 #393125

# magenta
color5                  #8a8976
color13                 #8a8976

# cyan
color6                  #4a4133
color14                 #4a4133

# white
color7                  #656456
color15                 #8a8a76

active_tab_foreground    #070605
active_tab_background    #393125
inactive_tab_foreground  #525146
inactive_tab_background  #1a1915

active_border_color      #393125
inactive_border_color    #2c2b25
bell_border_color        #7e6c5a
