# hyprland-colors.conf - Matugen base16

$fg = rgb(656456)
$bg = rgb(070605)

$border_active = rgb(525146)
$border_inactive = rgb(2c2b25)

$border_gradient_active = rgb(4a4133) rgb(393125) 45deg
$border_gradient_inactive = rgb(2c2b25) rgb(3f3e35) 45deg

$border_urgent = rgb(705b45)
