#
# Config by wurst1337, https://github.com/wurst1337/dots-hyprland
#

source = ~/.config/hypr/hyprland/autorun-execs.conf # autorun
source = ~/.config/hypr/hyprland/env.conf # env variables
source = ~/.config/hypr/hyprland/colors.conf # General cfg, for a monitor, look, animations and input
source = ~/.config/hypr/hyprland/general.conf # General cfg, for a monitor, look, animations and input
source = ~/.config/hypr/hyprland/rules.conf # Rules, like a floating for dialog windows
source = ~/.config/hypr/hyprland/vars.conf # Variables, like a default terminal
source = ~/.config/hypr/hyprland/binds.conf # binds (keyboard shortcuts)