# hyprland-colors.conf - Matugen base16

$fg = rgb({{base16.base05.default.hex_stripped}})
$bg = rgb({{base16.base00.default.hex_stripped}})

$border_active = rgb({{base16.base04.default.hex_stripped}})
$border_inactive = rgb({{base16.base02.default.hex_stripped}})

$border_gradient_active = rgb({{base16.base0c.default.hex_stripped}}) rgb({{base16.base0d.default.hex_stripped}}) 45deg
$border_gradient_inactive = rgb({{base16.base02.default.hex_stripped}}) rgb({{base16.base03.default.hex_stripped}}) 45deg

$border_urgent = rgb({{base16.base08.default.hex_stripped}})
