# kitty.conf - Matugen base16

foreground              {{base16.base05.default.hex}}
background              {{base16.base00.default.hex}}
cursor                  {{base16.base05.default.hex}}
cursor_text_color        {{base16.base00.default.hex}}

selection_foreground     {{base16.base05.default.hex}}
selection_background     {{base16.base02.default.hex}}

url_color                {{base16.base0d.default.hex}}

# black
color0                  {{base16.base00.default.hex}}
color8                  {{base16.base03.default.hex}}

# red
color1                  {{base16.base08.default.hex}}
color9                  {{base16.base08.default.hex}}

# green
color2                  {{base16.base0b.default.hex}}
color10                 {{base16.base0b.default.hex}}

# yellow
color3                  {{base16.base0a.default.hex}}
color11                 {{base16.base0a.default.hex}}

# blue
color4                  {{base16.base0d.default.hex}}
color12                 {{base16.base0d.default.hex}}

# magenta
color5                  {{base16.base0e.default.hex}}
color13                 {{base16.base0e.default.hex}}

# cyan
color6                  {{base16.base0c.default.hex}}
color14                 {{base16.base0c.default.hex}}

# white
color7                  {{base16.base05.default.hex}}
color15                 {{base16.base07.default.hex}}

active_tab_foreground    {{base16.base00.default.hex}}
active_tab_background    {{base16.base0d.default.hex}}
inactive_tab_foreground  {{base16.base04.default.hex}}
inactive_tab_background  {{base16.base01.default.hex}}

active_border_color      {{base16.base0d.default.hex}}
inactive_border_color    {{base16.base02.default.hex}}
bell_border_color        {{base16.base0a.default.hex}}
