exec-once = wal -R # Restore a pywal color schemes
exec-once = waybar # Run waybar
exec-once = awww-daemon  # Run wallpaper daemon
exec-once = hypridle # For idle and auto lock
exec-once = wl-paste --type text --watch cliphist store # To store clipboard
exec-once = wl-paste --type image --watch cliphist store # To Store clipboard
exec-once = ~/.config/hypr/scripts/auto-sunset.sh # To run auto-sunset
source = ~/.cache/wal/colors-hyprland.conf # import restored theme

## Fallback will be added in future.