#
# Config by wurst1337, https://github.com/wurst1337/dots-hyprland
#

# Monitor preferences (probably, you want to change on yours setting)
monitor=,preferred,auto,auto
# You can view info about your monitor using command: hyprctl monitors

#################
### MAIN LOOK ###
#################

general {
    gaps_in = 10
    gaps_out = 15
    gaps_workspaces = 50
    border_size = 3
    col.active_border = $color1 $color2 45deg # if you see error on this line, run wallmk <path_to_your_image>
    col.inactive_border = rgba(595959aa) # (may be changed by pywal)
    resize_on_border = true

    layout = dwindle
}

decoration {
    rounding = 10
    rounding_power = 2

    active_opacity = 1
    inactive_opacity = 1

    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }
    blur {
        enabled = false
        size = 3
        passes = 1

        vibrancy = 0.1696
    }
}

animations {
    bezier = easeOutQuint,   0.23, 1,    0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear,         0,    0,    1,    1
    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1
    animation = global,        1,     10,    default
    animation = border,        1,     5.39,  easeOutQuint
    animation = windows,       1,     4.79,  easeOutQuint
    animation = windowsIn,     1,     4.1,   easeOutQuint, popin 87%
    animation = windowsOut,    1,     1.49,  linear,       popin 87%
    animation = fadeIn,        1,     1.73,  almostLinear
    animation = fadeOut,       1,     1.46,  almostLinear
    animation = fade,          1,     3.03,  quick
    animation = layers,        1,     3.81,  easeOutQuint
    animation = layersIn,      1,     4,     easeOutQuint, fade
    animation = layersOut,     1,     1.5,   linear,       fade
    animation = fadeLayersIn,  1,     1.79,  almostLinear
    animation = fadeLayersOut, 1,     1.39,  almostLinear
    animation = workspaces,    1,     1.94,  easeInOutCubic, slidefade
    animation = workspacesIn,  1,     1.21,  easeInOutCubic, slidefade
    animation = workspacesOut, 1,     1.94,  easeInOutCubic, slidefade
    animation = zoomFactor,    1,     7,     quick
}


dwindle {
    pseudotile = true
    preserve_split = true 
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = true
}

#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us, ru
    kb_variant =
    kb_model =
    kb_options = grp:alt_shift_toggle
    kb_rules = 

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}
gesture = 3, horizontal, workspace
