windowrule = float on, match:modal true
windowrule = size (monitor_w*0.6) (monitor_h*0.6), match:modal true
windowrule = max_size 1400 1000, match:modal true

windowrule = float on, match:class ^GtkFileChooserDialog$
windowrule = center on, match:class ^GtkFileChooserDialog$

windowrule = float on, match:class ^(xdg-desktop-portal.*)$
windowrule = center on, match:class ^(xdg-desktop-portal.*)$

windowrule = float on, match:class ^(org.freedesktop.impl.portal.desktop.*)$
windowrule = center on, match:class ^(org.freedesktop.impl.portal.desktop.*)$

windowrule = float on, match:title ^(Open|Save|Save As|Choose|Select).*
windowrule = center on, match:title ^(Open|Save|Save As|Choose|Select).*

windowrule = float on, match:title ^(Preferences|Settings|Properties).*
windowrule = center on, match:title ^(Preferences|Settings|Properties).*

windowrule = float on, match:title ^(Confirm|Confirmation|Error|Warning).*
windowrule = center on, match:title ^(Confirm|Confirmation|Error|Warning).*

windowrule = float on, match:class ^pavucontrol$
windowrule = size 900 600, match:class ^pavucontrol$
windowrule = center on, match:class ^pavucontrol$

windowrule = float on, match:class ^pavucontrol-qt$
windowrule = size 900 600, match:class ^pavucontrol-qt$
windowrule = center on, match:class ^pavucontrol-qt$

windowrule = float on, match:class ^nm-connection-editor$
windowrule = center on, match:class ^nm-connection-editor$

windowrule = float on, match:class ^blueman-manager$
windowrule = float on, match:class ^blueman-adapters$
windowrule = center on, match:class ^blueman-.*

windowrule = float on, match:class ^(polkit-gnome-authentication-agent-1)$
windowrule = center on, match:class ^(polkit-gnome-authentication-agent-1)$

windowrule = float on, match:class ^(lxappearance)$
windowrule = center on, match:class ^(lxappearance)$

windowrule = float on, match:class ^(qt5ct|qt6ct)$
windowrule = center on, match:class ^(qt5ct|qt6ct)$

windowrule = float on, match:title ^(Developer Tools).*
windowrule = center on, match:title ^(Developer Tools).*

windowrule = float on, match:title ^(Picture-in-Picture).*
windowrule = pin on, match:title ^(Picture-in-Picture).*
windowrule = size 480 270, match:title ^(Picture-in-Picture).*
windowrule = move (monitor_w-500) (monitor_h-320), match:title ^(Picture-in-Picture).*

windowrule = rounding 10, match:float true
windowrule = border_size 2, match:float true

windowrule = float on, match:class ^(org.telegram.desktop)$, match:title ^(Media viewer).*
windowrule = center on, match:class ^(org.telegram.desktop)$, match:title ^(Media viewer).*

windowrule = float on, match:class ^discord$, match:title ^(User Settings).*
windowrule = center on, match:class ^discord$, match:title ^(User Settings).*

windowrule = no_max_size on, match:xwayland true