color0 #14140f
color1 #ffb4ab
color2 #c7cd5b
color3 #c8c9a6
color4 #a3d0bf
color5 #c7cd5b
color6 #c8c9a6
color7 #e5e2da
color8 #929182
color9 #ffb4ab
color10 #c7cd5b
color11 #c8c9a6
color12 #a3d0bf
color13 #c7cd5b
color14 #c8c9a6
color15 #e5e2da

cursor                #e5e2da
cursor_text_color     #14140f
background            #14140f
foreground            #e5e2da
selection_foreground  #c9c7b6
selection_background  #47473b
active_border_color   #c7cd5b
inactive_border_color #47473b
url_color             #c7cd5b

active_tab_foreground   #303300
active_tab_background   #c7cd5b
inactive_tab_foreground #c9c7b6
inactive_tab_background #47473b
cursor_trail_color      #c9c7b6
